name: Deploy Node + React App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: |
          cd client
          npm install
          npm run build

      - run: |
          cd ..
          npm install

      - uses: azure/webapps-deploy@v2
        with:
          app-name: jalarakshak
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
